{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: QControl
  version: v0.0.1
  author: Kurt  Jacobson
  description: >
    Not Much

data_plugins:
  status:
    kwargs:
      cycle_time: 75

windows:
  mainwindow:
    provider: qcontrol.qcontrol:QControlMainWindow
    kwargs:
      menu: ( default_menubar )
      ui_file: {{ file.dir }}/ui/qcontrol.ui

dialogs:
  feed_override_dialog: 
    provider: qtpyvcp.widgets.dialogs.base_dialog:BaseDialog
    kwargs:
      ui_file: {{ file.dir }}/dialogs/feed_override_dialog.ui
      modal: yes
      frameless: yes

  spindle_override_dialog: 
    provider: qtpyvcp.widgets.dialogs.base_dialog:BaseDialog
    kwargs:
      ui_file: {{ file.dir }}/dialogs/speed_override_dialog.ui
      modal: yes
      popup: yes

application:
  kwargs:
    theme: windows
    stylesheet: {{ file.dir }}/ui/qcontrol.qss
